# -*- coding: utf-8 -*-
"""aux_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136bSWdd3sfM6ytXJebF6ij3Zzz-h8w7j
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os
import matplotlib.pyplot as plt

st.set_page_config(page_title="Bank Marketing Prediction Dashboard", layout="wide")

# --------------------------------------------------
# Final FE v2 model comparison results
# --------------------------------------------------
results = pd.DataFrame({
    "Model": ["Logistic Regression", "Lasso Logistic", "Random Forest", "SVM (RBF)", "XGBoost"],
    "Accuracy": [0.8236, 0.8277, 0.8641, 0.8455, 0.8422],
    "Balanced_Accuracy": [0.7190, 0.7310, 0.7092, 0.7410, 0.7197],
    "Precision": [0.3278, 0.3388, 0.4035, 0.3727, 0.3585],
    "Recall": [0.5852, 0.6074, 0.5111, 0.6074, 0.5630],
    "F1": [0.4202, 0.4350, 0.4510, 0.4620, 0.4380],
    "ROC_AUC": [0.7670, 0.7895, 0.7759, 0.7676, 0.7696],
    "PR_AUC": [0.4006, 0.3963, 0.4191, 0.4112, 0.4176]
})

# --------------------------------------------------
# Feature engineering v2
# --------------------------------------------------
def engineer_features_v2(data):
    df_fe = data.copy()

    df_fe["ever_contacted_before"] = (df_fe["pdays"] != 999).astype(int)
    df_fe["never_contacted_before"] = (df_fe["pdays"] == 999).astype(int)
    df_fe["pdays_clean"] = np.where(df_fe["pdays"] == 999, 0, df_fe["pdays"])

    df_fe["prior_success"] = (df_fe["poutcome"] == "success").astype(int)
    df_fe["prior_failure"] = (df_fe["poutcome"] == "failure").astype(int)
    df_fe["prior_nonexistent"] = (df_fe["poutcome"] == "nonexistent").astype(int)

    def history_status(row):
        if row["pdays"] == 999:
            return "never_contacted"
        elif row["poutcome"] == "success":
            return "contacted_success"
        elif row["poutcome"] == "failure":
            return "contacted_failure"
        else:
            return "contacted_other"

    df_fe["history_status"] = df_fe.apply(history_status, axis=1)

    def previous_bin(x):
        if x == 0:
            return "0"
        elif x == 1:
            return "1"
        elif x == 2:
            return "2"
        elif 3 <= x <= 5:
            return "3_5"
        else:
            return "6_plus"

    df_fe["previous_bin"] = df_fe["previous"].apply(previous_bin)

    def campaign_bin(x):
        if x == 1:
            return "1"
        elif x == 2:
            return "2"
        elif x == 3:
            return "3"
        elif 4 <= x <= 5:
            return "4_5"
        else:
            return "6_plus"

    df_fe["campaign_bin"] = df_fe["campaign"].apply(campaign_bin)
    df_fe["high_campaign_pressure"] = (df_fe["campaign"] >= 4).astype(int)
    df_fe["very_high_campaign_pressure"] = (df_fe["campaign"] >= 6).astype(int)
    df_fe["first_time_contact"] = ((df_fe["campaign"] == 1) & (df_fe["previous"] == 0)).astype(int)

    def age_group(x):
        if x < 30:
            return "under_30"
        elif x < 40:
            return "30s"
        elif x < 50:
            return "40s"
        elif x < 60:
            return "50s"
        else:
            return "60_plus"

    df_fe["age_group"] = df_fe["age"].apply(age_group)
    df_fe["is_young"] = (df_fe["age"] < 30).astype(int)
    df_fe["is_senior"] = (df_fe["age"] >= 60).astype(int)

    unknown_cols = ["job", "marital", "education", "default", "housing", "loan"]
    for col in unknown_cols:
        df_fe[f"{col}_unknown_flag"] = (df_fe[col] == "unknown").astype(int)

    df_fe["any_unknown_info"] = (
        (df_fe["job"] == "unknown") |
        (df_fe["marital"] == "unknown") |
        (df_fe["education"] == "unknown") |
        (df_fe["default"] == "unknown") |
        (df_fe["housing"] == "unknown") |
        (df_fe["loan"] == "unknown")
    ).astype(int)

    df_fe["has_housing_loan"] = (df_fe["housing"] == "yes").astype(int)
    df_fe["has_personal_loan"] = (df_fe["loan"] == "yes").astype(int)
    df_fe["has_any_loan"] = ((df_fe["housing"] == "yes") | (df_fe["loan"] == "yes")).astype(int)
    df_fe["has_both_loans"] = ((df_fe["housing"] == "yes") & (df_fe["loan"] == "yes")).astype(int)
    df_fe["default_or_risk_flag"] = ((df_fe["default"] == "yes") | (df_fe["default"] == "unknown")).astype(int)

    def quarter_from_month(month):
        if month in ["jan", "feb", "mar"]:
            return "Q1"
        elif month in ["apr", "may", "jun"]:
            return "Q2"
        elif month in ["jul", "aug", "sep"]:
            return "Q3"
        else:
            return "Q4"

    def season_from_month(month):
        if month in ["dec", "jan", "feb"]:
            return "winter"
        elif month in ["mar", "apr", "may"]:
            return "spring"
        elif month in ["jun", "jul", "aug"]:
            return "summer"
        else:
            return "fall"

    df_fe["quarter"] = df_fe["month"].apply(quarter_from_month)
    df_fe["season"] = df_fe["month"].apply(season_from_month)

    df_fe["low_euribor_flag"] = (df_fe["euribor3m"] <= df_fe["euribor3m"].median()).astype(int)
    df_fe["low_confidence_flag"] = (df_fe["cons.conf.idx"] <= df_fe["cons.conf.idx"].median()).astype(int)
    df_fe["high_unemployment_proxy"] = (df_fe["emp.var.rate"] <= df_fe["emp.var.rate"].median()).astype(int)
    df_fe["macro_stress_flag"] = ((df_fe["low_euribor_flag"] == 1) & (df_fe["low_confidence_flag"] == 1)).astype(int)

    return df_fe

# --------------------------------------------------
# Load model
# --------------------------------------------------
MODEL_PATH = "artifacts/svm_best_pipeline.joblib"
model_loaded = os.path.exists(MODEL_PATH)
model = joblib.load(MODEL_PATH) if model_loaded else None

# --------------------------------------------------
# Sidebar navigation
# --------------------------------------------------
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["Project Overview", "Model Comparison", "Customer Prediction"])

# --------------------------------------------------
# Page 1: Overview
# --------------------------------------------------
if page == "Project Overview":
    st.title("Bank Marketing Subscription Prediction Dashboard")

    st.subheader("Project Summary")
    st.write("""
    This project predicts whether a bank client will subscribe to a term deposit using the UCI Bank Marketing dataset.
    The final version reorganized feature engineering into contact history, campaign pressure, demographic/profile,
    financial, and macroeconomic blocks, and compared several machine learning models under class imbalance.
    """)

    st.subheader("Main Result")
    st.success("The tuned SVM (RBF) achieved the strongest balanced overall performance after Feature Engineering v2.")

    st.subheader("Final Best Balanced Model")
    best_row = results.loc[results["Balanced_Accuracy"].idxmax()]
    st.dataframe(best_row.to_frame().T, use_container_width=True)

# --------------------------------------------------
# Page 2: Model Comparison
# --------------------------------------------------
elif page == "Model Comparison":
    st.title("Final Model Comparison (FE v2)")
    st.dataframe(results, use_container_width=True)

    chart_df = results.set_index("Model")[["Balanced_Accuracy", "Recall", "F1"]]

    fig, ax = plt.subplots(figsize=(10, 5))
    chart_df.plot(kind="bar", ax=ax)
    ax.set_title("Balanced Accuracy, Recall, and F1 by Model")
    ax.set_ylabel("Score")
    ax.set_ylim(0, 1.0)
    plt.xticks(rotation=20, ha="right")
    plt.tight_layout()
    st.pyplot(fig)

    st.subheader("Interpretation")
    st.write("""
    - Tuned SVM achieved the highest balanced accuracy.
    - Lasso Logistic remained a strong regularized baseline.
    - Random Forest achieved the highest precision.
    - XGBoost improved after revised feature engineering, but did not surpass tuned SVM.
    """)

# --------------------------------------------------
# Page 3: Customer Prediction
# --------------------------------------------------
elif page == "Customer Prediction":
    st.title("Customer-Level Prediction Tool")

    if not model_loaded:
        st.error("Model file not found. Please run main.py first and save artifacts/svm_best_pipeline.joblib")
    else:
        st.subheader("Enter Customer Information")

        col1, col2, col3 = st.columns(3)

        with col1:
            age = st.number_input("Age", min_value=18, max_value=95, value=35)
            job = st.selectbox("Job", ["admin.", "blue-collar", "entrepreneur", "housemaid", "management",
                                       "retired", "self-employed", "services", "student", "technician",
                                       "unemployed", "unknown"])
            marital = st.selectbox("Marital", ["married", "single", "divorced", "unknown"])
            education = st.selectbox("Education", ["basic.4y", "basic.6y", "basic.9y", "high.school",
                                                   "illiterate", "professional.course", "university.degree", "unknown"])
            default = st.selectbox("Default", ["no", "yes", "unknown"])

        with col2:
            housing = st.selectbox("Housing Loan", ["no", "yes", "unknown"])
            loan = st.selectbox("Personal Loan", ["no", "yes", "unknown"])
            contact = st.selectbox("Contact Type", ["cellular", "telephone"])
            month = st.selectbox("Month", ["mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"])
            day_of_week = st.selectbox("Day of Week", ["mon", "tue", "wed", "thu", "fri"])

        with col3:
            campaign = st.number_input("Campaign Contacts", min_value=1, max_value=50, value=2)
            pdays = st.number_input("Days Since Previous Contact (999 if never contacted)", min_value=0, max_value=999, value=999)
            previous = st.number_input("Previous Contacts", min_value=0, max_value=20, value=0)
            poutcome = st.selectbox("Previous Outcome", ["nonexistent", "failure", "success"])
            emp_var_rate = st.number_input("Employment Variation Rate", value=1.1)
            cons_price_idx = st.number_input("Consumer Price Index", value=93.994)
            cons_conf_idx = st.number_input("Consumer Confidence Index", value=-36.4)
            euribor3m = st.number_input("Euribor 3M", value=4.857)
            nr_employed = st.number_input("Number of Employees", value=5191.0)

        if st.button("Predict Subscription Probability"):
            input_df = pd.DataFrame([{
                "age": age,
                "job": job,
                "marital": marital,
                "education": education,
                "default": default,
                "housing": housing,
                "loan": loan,
                "contact": contact,
                "month": month,
                "day_of_week": day_of_week,
                "campaign": campaign,
                "pdays": pdays,
                "previous": previous,
                "poutcome": poutcome,
                "emp.var.rate": emp_var_rate,
                "cons.price.idx": cons_price_idx,
                "cons.conf.idx": cons_conf_idx,
                "euribor3m": euribor3m,
                "nr.employed": nr_employed,
                "duration": 0
            }])

            input_fe = engineer_features_v2(input_df)
            X_input = input_fe.drop(columns=["duration"], errors="ignore")

            prob = model.predict_proba(X_input)[0, 1]
            pred = int(prob >= 0.5)

            st.metric("Predicted Subscription Probability", f"{prob:.3f}")

            if pred == 1:
                st.success("Recommendation: Target this customer")
            else:
                st.warning("Recommendation: Do Not Target this customer")